image: "archlinux:latest"

lint:
  script:
    - pacman -Syu --needed --noconfirm make shellcheck
    - make check

test:
  script:
    - pacman -Syu --needed --noconfirm podman make
    - make test BATS_EXTRA_ARGS='--formatter junit'
  tags:
    - vm
  artifacts:
    reports:
      junit: coverage/bats-report.xml

code-coverage:
  script:
    - pacman -Syu --needed --noconfirm podman make jq
    - make test-coverage
    - jq -r '. |
        ["Percent covered", .percent_covered],
        ["Covered lines", .covered_lines],
        ["Total lines", .total_lines],
        ["Percent low", .percent_low],
        ["Percent high", .percent_high] | @tsv' coverage/bats.*/coverage.json
  tags:
    - vm
  coverage: '/Percent covered\s+\d+\.\d+/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/bats.*/cobertura.xml
